# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/code/latest_code/implementation_running/final_code_nexys/final_code_nexys/final_code_nexys.srcs/sources_1/bd/Bram_mem/ip/Bram_mem_blk_mem_gen_0_0/Bram_mem_blk_mem_gen_0_0.xci
# IP: The module: 'Bram_mem_blk_mem_gen_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/code/latest_code/implementation_running/final_code_nexys/final_code_nexys/final_code_nexys.srcs/sources_1/bd/Bram_mem/ip/Bram_mem_blk_mem_gen_0_0/Bram_mem_blk_mem_gen_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Bram_mem_blk_mem_gen_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: D:/code/latest_code/implementation_running/final_code_nexys/final_code_nexys/final_code_nexys.srcs/sources_1/bd/Bram_mem/ip/Bram_mem_blk_mem_gen_0_0/Bram_mem_blk_mem_gen_0_0.xci
# IP: The module: 'Bram_mem_blk_mem_gen_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/code/latest_code/implementation_running/final_code_nexys/final_code_nexys/final_code_nexys.srcs/sources_1/bd/Bram_mem/ip/Bram_mem_blk_mem_gen_0_0/Bram_mem_blk_mem_gen_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Bram_mem_blk_mem_gen_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
