# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constraint1.xdc

# Block Designs: bd/Bram_mem/Bram_mem.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Bram_mem || ORIG_REF_NAME==Bram_mem} -quiet] -quiet

# IP: bd/Bram_mem/ip/Bram_mem_blk_mem_gen_0_0/Bram_mem_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Bram_mem_blk_mem_gen_0_0 || ORIG_REF_NAME==Bram_mem_blk_mem_gen_0_0} -quiet] -quiet

# XDC: bd/Bram_mem/Bram_mem_ooc.xdc
