# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/code/latest_code/implementation_running/final_code_nexys/final_code_nexys/final_code_nexys.cache/wt [current_project]
set_property parent.project_path D:/code/latest_code/implementation_running/final_code_nexys/final_code_nexys/final_code_nexys.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:nexys4_ddr:part0:1.1 [current_project]
set_property ip_output_repo d:/code/latest_code/implementation_running/final_code_nexys/final_code_nexys/final_code_nexys.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files D:/code/latest_code/implementation_running/final_code_nexys/final_code_nexys/design_1_blk_mem_gen_0_0.coe
read_verilog -library xil_defaultlib {
  D:/code/latest_code/implementation_running/final_code_nexys/final_code_nexys/final_code_nexys.srcs/sources_1/imports/hdl/Bram_mem_wrapper.v
  D:/code/latest_code/implementation_running/final_code_nexys/final_code_nexys/final_code_nexys.srcs/sources_1/new/UART_TX.v
  D:/code/latest_code/implementation_running/final_code_nexys/final_code_nexys/final_code_nexys.srcs/sources_1/new/conv_gb.v
  D:/code/latest_code/implementation_running/final_code_nexys/final_code_nexys/final_code_nexys.srcs/sources_1/new/image_top_bram.v
}
add_files D:/code/latest_code/implementation_running/final_code_nexys/final_code_nexys/final_code_nexys.srcs/sources_1/bd/Bram_mem/Bram_mem.bd
set_property used_in_implementation false [get_files -all d:/code/latest_code/implementation_running/final_code_nexys/final_code_nexys/final_code_nexys.srcs/sources_1/bd/Bram_mem/ip/Bram_mem_blk_mem_gen_0_0/Bram_mem_blk_mem_gen_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all D:/code/latest_code/implementation_running/final_code_nexys/final_code_nexys/final_code_nexys.srcs/sources_1/bd/Bram_mem/Bram_mem_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/code/latest_code/implementation_running/final_code_nexys/final_code_nexys/final_code_nexys.srcs/constrs_1/new/constraint1.xdc
set_property used_in_implementation false [get_files D:/code/latest_code/implementation_running/final_code_nexys/final_code_nexys/final_code_nexys.srcs/constrs_1/new/constraint1.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top image_top_bram -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef image_top_bram.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file image_top_bram_utilization_synth.rpt -pb image_top_bram_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
