set_property SRC_FILE_INFO {cfile:D:/code/latest_code/implementation_running/final_code_nexys/final_code_nexys/final_code_nexys.srcs/constrs_1/new/constraint1.xdc rfile:../../../final_code_nexys.srcs/constrs_1/new/constraint1.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H17 [get_ports completed]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E3 [get_ports clk]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D4 [get_ports o_TX_Serial]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J15 [get_ports r_ctrl]
